create BillingAPI
yakrash/Billing pull request #4
Opened 2020-04-17 15:16 UTC by yakrash

2020-04-17 15:29 UTC, vladthelittleone commented on src/main/java/su/bzz/springcourse/BillingAPI.java
> +            System.out.println("Error");
тут должны логировать и пробрасывать exception

2020-04-17 15:30 UTC, vladthelittleone commented on src/main/java/su/bzz/springcourse/TransactionController.java
> +        this.listFinancialTransaction = billingAPI.listFinancialTransaction;
вот это странный мув. зачем так делать?

2020-04-17 15:30 UTC, vladthelittleone commented on src/main/java/su/bzz/springcourse/iBillingAPI.java
> +public interface iBillingAPI {
BlillingAPI
BillingAPIImpl

2020-04-17 15:30 UTC, vladthelittleone commented on src/main/java/su/bzz/springcourse/BillingAPI.java
> +    @Autowired
Зачем тут Autowired

2020-04-17 15:32 UTC, vladthelittleone commented on src/main/java/su/bzz/springcourse/TransactionController.java
> +        this.listFinancialTransaction = billingAPI.listFinancialTransaction;
нужно же задать billingAPI

2020-04-17 15:32 UTC, vladthelittleone commented on src/main/java/su/bzz/springcourse/BillingAPI.java
> +    List<FinancialTransaction> listFinancialTransaction;
Все поля приватные. Не забываем

2020-04-17 15:55 UTC, yakrash commented on src/main/java/su/bzz/springcourse/TransactionController.java
> +        this.listFinancialTransaction = billingAPI.listFinancialTransaction;
Да, здесь что-то я заморочился. Можно тогда убрать конструктор и создания листа и просто сделать так: 
@Autowired
    private BillingAPI billingAPI;

    @PostMapping("/transfer")
    ResponseEntity<?> create(@RequestBody FinancialTransaction financialTransaction) {
        billingAPI.transfer(financialTransaction);
        billingAPI.listFinancialTransaction.add(financialTransaction);
        return new ResponseEntity<>(HttpStatus.CREATED);
?

2020-04-17 16:03 UTC, yakrash commented on src/main/java/su/bzz/springcourse/TransactionController.java
> +        this.listFinancialTransaction = billingAPI.listFinancialTransaction;
если лист приватный в BillingAPI, то нельзя так

2020-04-17 16:08 UTC, yakrash commented on src/main/java/su/bzz/springcourse/TransactionController.java
> +        this.listFinancialTransaction = billingAPI.listFinancialTransaction;
вот так  тогда? 
`@Autowired
private BillingAPI billingAPI;

@PostMapping("/transfer")
ResponseEntity<?> create(@RequestBody FinancialTransaction financialTransaction) {
    billingAPI.transfer(financialTransaction);
    billingAPI.listadd(financialTransaction);
    return new ResponseEntity<>(HttpStatus.CREATED);
`

2020-04-17 21:19 UTC, vladthelittleone commented on src/main/java/su/bzz/springcourse/BillingAPIImpl.java
> +@Component
@Service

2020-04-17 21:20 UTC, vladthelittleone commented on src/main/java/su/bzz/springcourse/BillingAPIImpl.java
> +
Левые переносы

2020-04-17 21:20 UTC, vladthelittleone requested changes

2020-04-17 21:20 UTC, vladthelittleone commented on src/main/java/su/bzz/springcourse/TransactionValidator.java
> +            logger.info("Счет получателя не валидный");
logger.error

2020-04-17 21:20 UTC, vladthelittleone commented on src/main/java/su/bzz/springcourse/TransactionValidator.java
> +    private final static Logger logger = Logger.getLogger(TransactionValidator.class.getName());
перенос

2020-04-18 10:41 UTC, yakrash commented on src/main/java/su/bzz/springcourse/TransactionValidator.java
> +            logger.info("Счет получателя не валидный");
метод error не нашел в логгере, есть warning. Поменял на него

2020-04-19 12:20 UTC, merged